# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/ezplatform_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_ezplatform_sites:
  ezplatform.com:
    env:
      database_driver: pdo_mysql
      database_user: ezplatform
      database_name: ezplatform
      database_password: fh4gQ37L4CodnzLLr8
      database_host: localhost
