# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `ezplatform_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

ezplatform_sites:
  ezplatform.com:
    site_hosts:
      - canonical: ezplatform.com
        redirects:
          - www.ezplatform.com
#      - canonical: example.co.uk
#        redirects:
#          - www.example.co.uk
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:example/example.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
#      enabled: true
#      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
